### ISSUE TITLE
Installation issues (Ionic2)

### ISSUE THREAD

**Issue by graphefruit** [tomloprod/cordova-plugin-appminimize#6]
Installing the latest plugin remains into issue: 

Following command: `ionic cordova plugin add cordova-plugin-appminimize`
from [Ionic-Reference](http://ionicframework.com/docs/native/app-minimize/) leads to following issue:
```
C:\Users\Graphefruit\Documents\playground\play>ionic cordova plugin add cordova-plugin-appminimize
> cordova plugin add cordova-plugin-appminimize --save
× Running command - failed!
[ERROR] An error occurred while running cordova plugin add cordova-plugin-appminimize --save (exit code 1):


        Installing "cordova-plugin-appminimize" for android
        ANDROID_HOME=C:\Users\Graphefruit\AppData\Local\Android\sdk
        JAVA_HOME=C:\Program Files\Java\jdk1.8.0_112
        Subproject Path: CordovaLib
        The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use
        Task.doLast(Action) instead.
                at
        build_a325rxascvepsmnlocy1bmoss.run(C:\Users\Graphefruit\Documents\playground\play\platforms\android\build.gradle:138)
        The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
        Incremental java compilation is an incubating feature.
        The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please
        use TaskInputs.file(Object).skipWhenEmpty() instead.
        :clean FAILED

        BUILD FAILED

        Total time: 9.025 secs

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':clean'.
        > Unable to delete directory:
        C:\Users\Graphefruit\Documents\playground\play\platforms\android\build\outputs\apk\android-debug\res

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
        Picked up _JAVA_OPTIONS: -Xmx512M
        Failed to install 'cordova-plugin-appminimize': Error: cmd: Command failed with exit code 1
             at ChildProcess.whenDone
        (C:\Users\Graphefruit\Documents\playground\play\platforms\android\cordova\node_modules\cordova-common\src\superspawn.js:169:23)
             at emitTwo (events.js:106:13)
             at ChildProcess.emit (events.js:191:7)
             at maybeClose (internal/child_process.js:920:16)
             at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
        Error: cmd: Command failed with exit code 1
```
Any ideas?

**Comment by graphefruit** [comment]
Ok found it.
Task couldn't delete the APK-directory and then failed completly.
When removing the APK-directory its working.
